require 'plugins.mini.ai'
require 'plugins.mini.git'
require 'plugins.mini.icons'
require 'plugins.mini.misc'
require 'plugins.mini.notify'
require 'plugins.mini.statusline'
require 'plugins.mini.surround'
