-- https://github.com/golang/tools/blob/master/gopls/doc/settings.md
-- https://github.com/golang/tools/blob/master/gopls/doc/semantictokens.md
return {
  -- https://github.com/mvdan/gofumpt/issues/2
  -- https://github.com/mvdan/gofumpt/pull/70
  -- cmd_env = {
  --   GOFUMPT_SPLIT_LONG_LINES = 'on',
  -- },
  -- filetypes = { 'go', 'gomod', 'gowork', 'gotmpl', 'gohtmltmpl', 'gotexttmpl' },
  -- filetypes = { 'go', 'gomod', 'gowork', 'totmpl' },
  cmd = { 'gopls', '--remote=auto' },
  settings = {
    gopls = {
      -- useful for -tags (and other things)
      -- buildFlags = nil,
      -- directoryFilters = { '+go' },
      -- templateExtensions = { 'gohtml', 'gotoml' },
      ['local'] = '',
      gofumpt = true,
      usePlaceholders = false,
      experimentalPostfixCompletions = true,
      completeFunctionCalls = true,
      semanticTokens = true,
      -- turn off semantic token strings when using injections,
      -- otherwise it overrides ts injections for sql (and others)
      -- noSemanticString = true,
      -- noSemanticNumber = true,
      staticcheck = true,
      hoverKind = 'FullDocumentation',
      vulncheck = 'Imports',
      analysisProgressReporting = true,
      hints = {
        assignVariableTypes = false,
        compositeLiteralFields = false,
        compositeLiteralTypes = false,
        constantValues = true,
        functionTypeParameters = false,
        parameterNames = false,
        rangeVariableTypes = false,
      },
      analyses = {
        appends = true,
        asmdecl = true,
        assign = true,
        atomic = true,
        atomicalign = true,
        bools = true,
        buildtag = true,
        cgocall = true,
        composites = true,
        copylocks = true,
        deepequalerrors = true,
        defers = true,
        deprecated = true,
        directive = true,
        embed = true,
        errorsas = true,
        fillreturns = true,
        framepointer = true,
        httpresponse = true,
        ifaceassert = true,
        infertypeargs = true,
        loopclosure = true,
        lostcancel = true,
        nilfunc = true,
        nilness = true,
        nonewvars = true,
        noresultvalues = true,
        printf = true,
        shadow = true,
        shift = true,
        sigchanyzer = true,
        simplifycompositelit = true,
        simplifyrange = true,
        simplifyslice = true,
        slog = true,
        sortslice = true,
        stdmethods = true,
        stdversion = true,
        stringintconv = true,
        structtag = true,
        testinggoroutine = true,
        tests = true,
        timeformat = true,
        unmarshal = true,
        unreachable = true,
        unsafeptr = true,
        unusedparams = true,
        unusedresult = true,
        unusedwrite = true,
        useany = true,
        waitgroup = true,
        yield = true,
      },
      codelenses = {
        gc_details = true,
        generate = true,
        regenerate_cgo = false,
        test = true,
        tidy = true,
        upgrade_dependency = true,
        vendor = true,
      },
    },
  },
}
